### ISSUE TITLE
some changes to make this work.

### ISSUE THREAD

**Issue by evanrich** [wnielson/Plex-Bandwidth-Monitor#2]
Followed your directions, but it didn't work at first in freebsd...had to do the following:

change "eth0" to "epair1b", since I'm in a jail.  Might want to grab the interface from the os so it's dynamic.
set IP for plexhost and token  (PLEX_HOST  = "192.168.1.20:32400")

However with these in place, while the script runs, generates a database, I don't see any stats showing up, and the sessions table is empty.   To troubleshoot, I tried opening the url that you construct:
`(http://192.168.1.20:32400/status/sessions?X-Plex-Token=<token>)`

And I get a session list, so it should be able to parse the sessions data but it doesn't seem to, running "python plex_bwmon.py" just sits there like it's doing something, but I don't see any activity.  Glad to help troubleshoot anyway i can.

edit:  actually it finally bombed out:

> Traceback (most recent call last):
>   File "plex_bwmon.py", line 285, in <module>
>     run()
>   File "plex_bwmon.py", line 266, in run
>     expired_sessions = update_sessions(sessions)
>   File "plex_bwmon.py", line 90, in update_sessions
>     res = urllib.urlopen(urlparse.urljoin(PLEX_HOST, "/status/sessions?X-Plex-Token=%s" % PLEX_TOKEN))
>   File "/usr/local/lib/python2.7/urllib.py", line 87, in urlopen
>     return opener.open(url)
>   File "/usr/local/lib/python2.7/urllib.py", line 213, in open
>     return getattr(self, name)(url)
>   File "/usr/local/lib/python2.7/urllib.py", line 469, in open_file
>     return self.open_local_file(url)
>   File "/usr/local/lib/python2.7/urllib.py", line 483, in open_local_file
>     raise IOError(e.errno, e.strerror, e.filename)
> IOError: [Errno 2] No such file or directory: '/status/sessions?X-Plex-Token=<token>'

setting this also doesn't seem to help:
>  res = urllib.urlopen("http://192.168.1.20:32400/status/sessions?X-Plex-Token=redacted")

**Comment by evanrich** [comment]
looks like it's working better with latest updates,  great work!  I don't have it output to screen (can't figure out why), but if i background it, i am getting entires into the DB

**Comment by phaelon74** [comment]
@evanrich how did you get your Plex Token?  I can't find it/get it through the web app when clicking on get more information.  Any help would rock!

**Comment by evanrich** [comment]
@phaelon74  you get it from your library.  click a library, view an item (tv/movie/etc) and select "get info", then select "view  xml"... the URL you get has the token at the end: 
![image](https://user-images.githubusercontent.com/518320/45986717-134c7900-c022-11e8-9efe-bcb1d295af27.png)
